Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: ${self:custom.kinesisStream}
      StreamModeDetails:
        StreamMode: ON_DEMAND

Outputs:
  KinesisStreamName:
    Value:
      Ref: KinesisStream
