Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: ${self:custom.kinesisStream}
      ShardCount: 1

Outputs:
  KinesisStreamName:
    Value:
      Ref: KinesisStream
